development:
  dialect: postgres
  database: bookings
  user: admin
  password: 1234
  host: 139.144.78.90
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@139.144.78.90:5432/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@139.144.78.90:5432/myapp_production"}}